import Navbar from "@/components/Common/Navbar/Navbar";
import { Geist, Geist_Mono } from "next/font/google";

export const metadata = {
  title: "Dentist DNA",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  if (typeof children === "undefined" || children === null) {
    throw new Error("Children is undefined or null");
  }

  return (
    <main className="pt-20">
      <section>{children}</section>
    </main>
  );
}
